services:
  # Frontend Static Site
  - type: web
    name: moodscape-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://moodscape-backend.onrender.com/api
      - key: REACT_APP_ENVIRONMENT
        value: production
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 